<?php
/**
 * HMAC-SHA256 webhook signing helper for LuluDesk.
 *
 * Handles signing outgoing webhook requests from WordPress to LuluDesk.
 * The signature scheme is:
 *
 *   payload  = timestamp . "." . json_encoded_body
 *   signature = "sha256=" . hash_hmac( "sha256", payload, wp_api_key )
 *
 * The server verifies the signature using the same algorithm.
 * Timestamp is included to prevent replay attacks (server rejects >5 min old).
 *
 * @package LuluDesk_Chat_Memory
 * @since   1.1.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class LuluDesk_Webhook
 *
 * Signs and dispatches webhook requests to LuluDesk.
 * Designed to be easy to unit-test: pass a custom endpoint or api_key
 * via the constructor.
 */
class LuluDesk_Webhook {

	/**
	 * LuluDesk webhook endpoint URL.
	 *
	 * @var string
	 */
	const WEBHOOK_ENDPOINT = 'https://luluclaw.com/api/integrations/wordpress/webhook';

	/**
	 * LuluDesk full-sync endpoint URL.
	 *
	 * @var string
	 */
	const FULL_SYNC_ENDPOINT = 'https://luluclaw.com/api/integrations/wordpress/full-sync';

	/**
	 * The wp_api_key stored in options.
	 * Plain-text for v1 (WP has no native encryption API).
	 *
	 * @var string
	 */
	private $api_key;

	/**
	 * The kb_source_id for this WP site.
	 *
	 * @var string
	 */
	private $kb_source_id;

	/**
	 * Constructor.
	 *
	 * @param string $api_key      The wp_api_key generated by LuluDesk on /connect.
	 * @param string $kb_source_id UUID of the kb_sources row.
	 */
	public function __construct( $api_key, $kb_source_id ) {
		$this->api_key      = $api_key;
		$this->kb_source_id = $kb_source_id;
	}

	/**
	 * Builds the HMAC-SHA256 signature for a webhook payload.
	 *
	 * @param int    $timestamp Unix timestamp (seconds).
	 * @param string $body_json JSON-encoded request body string.
	 * @return string "sha256=<hex>"
	 */
	public function sign( $timestamp, $body_json ) {
		$payload   = $timestamp . '.' . $body_json;
		$signature = hash_hmac( 'sha256', $payload, $this->api_key );
		return 'sha256=' . $signature;
	}

	/**
	 * Dispatches an async (non-blocking) webhook POST to LuluDesk.
	 *
	 * Uses `blocking => false` so the WP admin save flow is not slowed down.
	 * Failures are silently logged — the plugin should never surface errors
	 * to non-technical WP admins during post saves.
	 *
	 * @param array $payload Associative array to JSON-encode and send.
	 * @return bool True when the request was dispatched; false on WP error.
	 */
	public function dispatch( array $payload ) {
		if ( empty( $this->api_key ) || empty( $this->kb_source_id ) ) {
			return false;
		}

		// Inject kb_source_id so the server can look up the source row.
		$payload['kb_source_id'] = $this->kb_source_id;

		$timestamp = time();
		$body_json = wp_json_encode( $payload );

		if ( false === $body_json ) {
			return false;
		}

		$signature = $this->sign( $timestamp, $body_json );

		$response = wp_remote_post(
			self::WEBHOOK_ENDPOINT,
			array(
				'method'    => 'POST',
				'timeout'   => 5,
				'blocking'  => false,   // Fire-and-forget — do NOT slow WP admin save.
				'headers'   => array(
					'Content-Type'         => 'application/json',
					'X-LuluDesk-Signature' => $signature,
					'X-LuluDesk-Timestamp' => (string) $timestamp,
				),
				'body'      => $body_json,
			)
		);

		if ( is_wp_error( $response ) ) {
			// Non-fatal: log but do not propagate.
			error_log( '[LuluDesk] Webhook dispatch error: ' . $response->get_error_message() );
			return false;
		}

		return true;
	}

	/**
	 * Helper: creates a LuluDesk_Webhook instance from stored WP options.
	 *
	 * Returns null when either required option is missing (KB not connected).
	 *
	 * @return LuluDesk_Webhook|null
	 */
	public static function from_options() {
		$api_key      = get_option( 'luludesk_wp_api_key', '' );
		$kb_source_id = get_option( 'luludesk_kb_source_id', '' );

		if ( empty( $api_key ) || empty( $kb_source_id ) ) {
			return null;
		}

		return new self( $api_key, $kb_source_id );
	}
}
